name: notify

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 9 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go get .

      - name: Run
        run: go run .
        env:
          # Discord API
          D_BOT_TOKEN: ${{ secrets.D_BOT_TOKEN }}
          D_A1_CHANNEL_ID: ${{ secrets.D_A1_CHANNEL_ID }}
          D_A2_CHANNEL_ID: ${{ secrets.D_A2_CHANNEL_ID }}
          D_ROLE_ID: ${{ secrets.D_ROLE_ID }}
          # Google Calendar API
          G_CALENDAR_ID: ${{ secrets.G_CALENDAR_ID }}
          G_CREDENTIALS: ${{ secrets.G_CREDENTIALS }}
